### ISSUE TITLE
See Image of Donuts

### ISSUE THREAD

**Issue by mahithedula** [CMU-17-356/dronuts-2023-krispykopters#22]
Card:
As a hungry donut-seeker, I want to see an image of the donuts available for purchase so I can pick the one that looks the most appetizing.

Conversation:
It should be clear which image depicts which donut no matter the device
Donut shops should be able to upload their own image (but this should probably be its own user story)
Each donut must have an image to ensure consistency and good UI

Confirmation:
If we open the application and we can clearly see the images for each donut and the images match the donut they are depicting.

**Comment by JunTaoLuo** [comment]
This looks identical to https://github.com/CMU-17-356/dronuts-2023-krispykopters/issues/6, maybe you posted the wrong user story?

**Comment by mahithedula** [comment]
> This looks identical to #6, maybe you posted the wrong user story?

Thanks for catching that

**Comment by JunTaoLuo** [comment]
Completed as of sprint 1 release
