### ISSUE TITLE
Donut Availability

### ISSUE THREAD

**Issue by mahithedula** [CMU-17-356/dronuts-2023-krispykopters#23]
Card: 
As a hungry customer, I want to see which donuts are available for drone delivery at the current moment, so that I can decide if I want to order donuts.

Conversation:
The donut shop’s donut menu should have real-time access to the donut shop’s inventory.

Confirmation:
I can view a list of donuts currently available for drone delivery and make a decision on whether or not to place an order.

**Comment by Bwillia2** [comment]
similar to #12
