### ISSUE TITLE
Receive Payments

### ISSUE THREAD

**Issue by mahithedula** [CMU-17-356/dronuts-2023-krispykopters#25]
Card:  
As a donut shop owner, I want to receive payments from customers, so that I can get paid for my product.

Conversation:
CommerceFried should relay user’s payments for their orders to the donut shop with details of the associated order.

Confirmation:
The donut shop can see the money from an order hit their account after an order is made.

**Comment by JunTaoLuo** [comment]
Potential duplicate of https://github.com/CMU-17-356/dronuts-2023-krispykopters/issues/4

**Comment by Bwillia2** [comment]
agreed, same as #4
