### ISSUE TITLE
See Price of Donuts

### ISSUE THREAD

**Issue by mahithedula** [CMU-17-356/dronuts-2023-krispykopters#6]
Card:
As a frugal donut-seeker, I want to see the prices of potential donuts I can purchase so I can make the appropriate choice based on my current financial situation.

Conversation:
The prices should be next to the donut so that the price of each donut is clear.
The price should be large enough to see no matter the device.
Donut shops should be able to update the prices of their donuts (but this should probably be its own user story).
The price should be in US dollars, no need to deal with currency conversion.

Confirmation:
If we open the application and can clearly see the prices of the donut and these prices match those of the donut shop.

**Comment by JunTaoLuo** [comment]
Completed as of sprint 1 release
