### ISSUE TITLE
Extra Credit Point - Add Drone Location

### ISSUE THREAD

**Issue by Joseph-ljx** [CMU-17-356/dronuts-2023-krispykopters#63]
Conversation:

As a shop owner, I would like to know where the drones are so I know when they will return and be ready for the next order.

Conversation:

Let's explore different map UI APIs for react

Confirmation:

A map with drone overlays is visible on the employee page.

**Comment by Joseph-ljx** [comment]
Its for the owner of the shop, not the map tracking for the customer

**Comment by Joseph-ljx** [comment]
Optionally, you may choose to implement a map to show where the drones are, and how they are moving to deliveries. If you choose to implement this, you will receive 10 extra credit points.

**Comment by Joseph-ljx** [comment]
Invole in getting the drones information and making that movement on the map

**Comment by JunTaoLuo** [comment]
Completed in #67
