### ISSUE TITLE
Integrating donut display with backend

### ISSUE THREAD

**Issue by mahithedula** [CMU-17-356/dronuts-2023-krispykopters#64]
Card:

As a user, I would like to see the menu with updated items (quantity, price, etc) so I can be more informed on what to order.

Conversation:

We need to integrate the donut display with the backend so the donuts stored in the database are shown. 
We also need to ensure that once an order has been placed, the front-end is updated so that the donut quantity goes down./
Refreshes once a minute so it can take in new updates from the admin store. 

We'll remove the menu page since it has duplicate functionalities of the home page.

Confirmation:

The user is happy with using the menu interface.

**Comment by JunTaoLuo** [comment]
We'll remove the refresh requirement since this is a rather bizarre behaviour (having the page randomly refresh).
