### ISSUE TITLE
Connect orders from the backend to the Drone Command Center

### ISSUE THREAD

**Issue by Bwillia2** [CMU-17-356/dronuts-2023-krispykopters#65]
Card:

As a store owner, I want to be able to fulfill orders once I load donuts into drones so that the customers can be notified that their donuts are on the way.

Conversation:

- Display all relevant information from the existing orders in MongoDB on the order cards in the Front-end on the Drone Command Center page.
- Once orders are fulfilled via the button in the command center, update the backend data.
- Integrate with the DroneAPI: https://cmu-17-356.github.io/project/drone_api/

Confirmation:

The orders can be easily tracked by the store owners and customers for updates on fulfillment and delivery.

**Comment by JunTaoLuo** [comment]
This was done in #79
